#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OspedaleEVaccinazioni
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Covid19Tracker")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definizioni metodo Extensibility
    partial void OnCreated();
    partial void Insertdosi(dosi instance);
    partial void Updatedosi(dosi instance);
    partial void Deletedosi(dosi instance);
    partial void Insertfornitore(fornitore instance);
    partial void Updatefornitore(fornitore instance);
    partial void Deletefornitore(fornitore instance);
    partial void Insertinfermiere(infermiere instance);
    partial void Updateinfermiere(infermiere instance);
    partial void Deleteinfermiere(infermiere instance);
    partial void Insertospedale(ospedale instance);
    partial void Updateospedale(ospedale instance);
    partial void Deleteospedale(ospedale instance);
    partial void Insertpaziente(paziente instance);
    partial void Updatepaziente(paziente instance);
    partial void Deletepaziente(paziente instance);
    partial void Insertpatologia(patologia instance);
    partial void Updatepatologia(patologia instance);
    partial void Deletepatologia(patologia instance);
    partial void Insertresidenza(residenza instance);
    partial void Updateresidenza(residenza instance);
    partial void Deleteresidenza(residenza instance);
    partial void Insertvaccinazione(vaccinazione instance);
    partial void Updatevaccinazione(vaccinazione instance);
    partial void Deletevaccinazione(vaccinazione instance);
    partial void Insertvaccino(vaccino instance);
    partial void Updatevaccino(vaccino instance);
    partial void Deletevaccino(vaccino instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::OspedaleEVaccinazioni.Properties.Settings.Default.Covid19TrackerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dosi> dosi
		{
			get
			{
				return this.GetTable<dosi>();
			}
		}
		
		public System.Data.Linq.Table<fornitore> fornitore
		{
			get
			{
				return this.GetTable<fornitore>();
			}
		}
		
		public System.Data.Linq.Table<infermiere> infermiere
		{
			get
			{
				return this.GetTable<infermiere>();
			}
		}
		
		public System.Data.Linq.Table<ospedale> ospedale
		{
			get
			{
				return this.GetTable<ospedale>();
			}
		}
		
		public System.Data.Linq.Table<paziente> paziente
		{
			get
			{
				return this.GetTable<paziente>();
			}
		}
		
		public System.Data.Linq.Table<patologia> patologia
		{
			get
			{
				return this.GetTable<patologia>();
			}
		}
		
		public System.Data.Linq.Table<residenza> residenza
		{
			get
			{
				return this.GetTable<residenza>();
			}
		}
		
		public System.Data.Linq.Table<vaccinazione> vaccinazione
		{
			get
			{
				return this.GetTable<vaccinazione>();
			}
		}
		
		public System.Data.Linq.Table<vaccino> vaccino
		{
			get
			{
				return this.GetTable<vaccino>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="covid19vaccinetracker.dosi")]
	public partial class dosi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVaccino;
		
		private int _IdOspedale;
		
		private int _TotDosi;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVaccinoChanging(int value);
    partial void OnIdVaccinoChanged();
    partial void OnIdOspedaleChanging(int value);
    partial void OnIdOspedaleChanged();
    partial void OnTotDosiChanging(int value);
    partial void OnTotDosiChanged();
    #endregion
		
		public dosi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVaccino", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdVaccino
		{
			get
			{
				return this._IdVaccino;
			}
			set
			{
				if ((this._IdVaccino != value))
				{
					this.OnIdVaccinoChanging(value);
					this.SendPropertyChanging();
					this._IdVaccino = value;
					this.SendPropertyChanged("IdVaccino");
					this.OnIdVaccinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOspedale", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdOspedale
		{
			get
			{
				return this._IdOspedale;
			}
			set
			{
				if ((this._IdOspedale != value))
				{
					this.OnIdOspedaleChanging(value);
					this.SendPropertyChanging();
					this._IdOspedale = value;
					this.SendPropertyChanged("IdOspedale");
					this.OnIdOspedaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotDosi", DbType="Int NOT NULL")]
		public int TotDosi
		{
			get
			{
				return this._TotDosi;
			}
			set
			{
				if ((this._TotDosi != value))
				{
					this.OnTotDosiChanging(value);
					this.SendPropertyChanging();
					this._TotDosi = value;
					this.SendPropertyChanged("TotDosi");
					this.OnTotDosiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="covid19vaccinetracker.fornitore")]
	public partial class fornitore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFornitore;
		
		private string _NomeFornitore;
		
		private string _Telefono;
		
		private int _IdVaccino;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFornitoreChanging(int value);
    partial void OnIdFornitoreChanged();
    partial void OnNomeFornitoreChanging(string value);
    partial void OnNomeFornitoreChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnIdVaccinoChanging(int value);
    partial void OnIdVaccinoChanged();
    #endregion
		
		public fornitore()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFornitore", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdFornitore
		{
			get
			{
				return this._IdFornitore;
			}
			set
			{
				if ((this._IdFornitore != value))
				{
					this.OnIdFornitoreChanging(value);
					this.SendPropertyChanging();
					this._IdFornitore = value;
					this.SendPropertyChanged("IdFornitore");
					this.OnIdFornitoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeFornitore", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string NomeFornitore
		{
			get
			{
				return this._NomeFornitore;
			}
			set
			{
				if ((this._NomeFornitore != value))
				{
					this.OnNomeFornitoreChanging(value);
					this.SendPropertyChanging();
					this._NomeFornitore = value;
					this.SendPropertyChanged("NomeFornitore");
					this.OnNomeFornitoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVaccino", DbType="Int NOT NULL")]
		public int IdVaccino
		{
			get
			{
				return this._IdVaccino;
			}
			set
			{
				if ((this._IdVaccino != value))
				{
					this.OnIdVaccinoChanging(value);
					this.SendPropertyChanging();
					this._IdVaccino = value;
					this.SendPropertyChanged("IdVaccino");
					this.OnIdVaccinoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="covid19vaccinetracker.infermiere")]
	public partial class infermiere : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdInfermiere;
		
		private string _Nome;
		
		private string _Cognome;
		
		private System.DateTime _DataNascita;
		
		private char _Sesso;
		
		private string _CodFiscale;
		
		private string _Telefono;
		
		private string _Mail;
		
		private System.DateTime _DataAssunzione;
		
		private int _IdOspedale;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdInfermiereChanging(int value);
    partial void OnIdInfermiereChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCognomeChanging(string value);
    partial void OnCognomeChanged();
    partial void OnDataNascitaChanging(System.DateTime value);
    partial void OnDataNascitaChanged();
    partial void OnSessoChanging(char value);
    partial void OnSessoChanged();
    partial void OnCodFiscaleChanging(string value);
    partial void OnCodFiscaleChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnDataAssunzioneChanging(System.DateTime value);
    partial void OnDataAssunzioneChanged();
    partial void OnIdOspedaleChanging(int value);
    partial void OnIdOspedaleChanged();
    #endregion
		
		public infermiere()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInfermiere", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdInfermiere
		{
			get
			{
				return this._IdInfermiere;
			}
			set
			{
				if ((this._IdInfermiere != value))
				{
					this.OnIdInfermiereChanging(value);
					this.SendPropertyChanging();
					this._IdInfermiere = value;
					this.SendPropertyChanged("IdInfermiere");
					this.OnIdInfermiereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this.OnCognomeChanging(value);
					this.SendPropertyChanging();
					this._Cognome = value;
					this.SendPropertyChanged("Cognome");
					this.OnCognomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascita", DbType="Date NOT NULL")]
		public System.DateTime DataNascita
		{
			get
			{
				return this._DataNascita;
			}
			set
			{
				if ((this._DataNascita != value))
				{
					this.OnDataNascitaChanging(value);
					this.SendPropertyChanging();
					this._DataNascita = value;
					this.SendPropertyChanged("DataNascita");
					this.OnDataNascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sesso", DbType="NChar(1) NOT NULL")]
		public char Sesso
		{
			get
			{
				return this._Sesso;
			}
			set
			{
				if ((this._Sesso != value))
				{
					this.OnSessoChanging(value);
					this.SendPropertyChanging();
					this._Sesso = value;
					this.SendPropertyChanged("Sesso");
					this.OnSessoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodFiscale", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string CodFiscale
		{
			get
			{
				return this._CodFiscale;
			}
			set
			{
				if ((this._CodFiscale != value))
				{
					this.OnCodFiscaleChanging(value);
					this.SendPropertyChanging();
					this._CodFiscale = value;
					this.SendPropertyChanged("CodFiscale");
					this.OnCodFiscaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAssunzione", DbType="Date NOT NULL")]
		public System.DateTime DataAssunzione
		{
			get
			{
				return this._DataAssunzione;
			}
			set
			{
				if ((this._DataAssunzione != value))
				{
					this.OnDataAssunzioneChanging(value);
					this.SendPropertyChanging();
					this._DataAssunzione = value;
					this.SendPropertyChanged("DataAssunzione");
					this.OnDataAssunzioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOspedale", DbType="Int NOT NULL")]
		public int IdOspedale
		{
			get
			{
				return this._IdOspedale;
			}
			set
			{
				if ((this._IdOspedale != value))
				{
					this.OnIdOspedaleChanging(value);
					this.SendPropertyChanging();
					this._IdOspedale = value;
					this.SendPropertyChanged("IdOspedale");
					this.OnIdOspedaleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="covid19vaccinetracker.ospedale")]
	public partial class ospedale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdOspedale;
		
		private string _Nome;
		
		private string _Indirizzo;
		
		private string _Telefono;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdOspedaleChanging(int value);
    partial void OnIdOspedaleChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnIndirizzoChanging(string value);
    partial void OnIndirizzoChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    #endregion
		
		public ospedale()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOspedale", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdOspedale
		{
			get
			{
				return this._IdOspedale;
			}
			set
			{
				if ((this._IdOspedale != value))
				{
					this.OnIdOspedaleChanging(value);
					this.SendPropertyChanging();
					this._IdOspedale = value;
					this.SendPropertyChanged("IdOspedale");
					this.OnIdOspedaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NChar(40) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indirizzo", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string Indirizzo
		{
			get
			{
				return this._Indirizzo;
			}
			set
			{
				if ((this._Indirizzo != value))
				{
					this.OnIndirizzoChanging(value);
					this.SendPropertyChanging();
					this._Indirizzo = value;
					this.SendPropertyChanged("Indirizzo");
					this.OnIndirizzoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="covid19vaccinetracker.paziente")]
	public partial class paziente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPaziente;
		
		private string _Nome;
		
		private string _Cognome;
		
		private System.DateTime _DataNascita;
		
		private char _Sesso;
		
		private string _CodFiscale;
		
		private string _Telefono;
		
		private string _Mail;
		
		private int _IdResidenza;
		
		private int _IdVaccino;
		
		private System.Nullable<int> _IdPatologia;
		
		private int _IdOspedale;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPazienteChanging(int value);
    partial void OnIdPazienteChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCognomeChanging(string value);
    partial void OnCognomeChanged();
    partial void OnDataNascitaChanging(System.DateTime value);
    partial void OnDataNascitaChanged();
    partial void OnSessoChanging(char value);
    partial void OnSessoChanged();
    partial void OnCodFiscaleChanging(string value);
    partial void OnCodFiscaleChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnIdResidenzaChanging(int value);
    partial void OnIdResidenzaChanged();
    partial void OnIdVaccinoChanging(int value);
    partial void OnIdVaccinoChanged();
    partial void OnIdPatologiaChanging(System.Nullable<int> value);
    partial void OnIdPatologiaChanged();
    partial void OnIdOspedaleChanging(int value);
    partial void OnIdOspedaleChanged();
    #endregion
		
		public paziente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPaziente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPaziente
		{
			get
			{
				return this._IdPaziente;
			}
			set
			{
				if ((this._IdPaziente != value))
				{
					this.OnIdPazienteChanging(value);
					this.SendPropertyChanging();
					this._IdPaziente = value;
					this.SendPropertyChanged("IdPaziente");
					this.OnIdPazienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this.OnCognomeChanging(value);
					this.SendPropertyChanging();
					this._Cognome = value;
					this.SendPropertyChanged("Cognome");
					this.OnCognomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascita", DbType="Date NOT NULL")]
		public System.DateTime DataNascita
		{
			get
			{
				return this._DataNascita;
			}
			set
			{
				if ((this._DataNascita != value))
				{
					this.OnDataNascitaChanging(value);
					this.SendPropertyChanging();
					this._DataNascita = value;
					this.SendPropertyChanged("DataNascita");
					this.OnDataNascitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sesso", DbType="NChar(1) NOT NULL")]
		public char Sesso
		{
			get
			{
				return this._Sesso;
			}
			set
			{
				if ((this._Sesso != value))
				{
					this.OnSessoChanging(value);
					this.SendPropertyChanging();
					this._Sesso = value;
					this.SendPropertyChanged("Sesso");
					this.OnSessoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodFiscale", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string CodFiscale
		{
			get
			{
				return this._CodFiscale;
			}
			set
			{
				if ((this._CodFiscale != value))
				{
					this.OnCodFiscaleChanging(value);
					this.SendPropertyChanging();
					this._CodFiscale = value;
					this.SendPropertyChanged("CodFiscale");
					this.OnCodFiscaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdResidenza", DbType="Int NOT NULL")]
		public int IdResidenza
		{
			get
			{
				return this._IdResidenza;
			}
			set
			{
				if ((this._IdResidenza != value))
				{
					this.OnIdResidenzaChanging(value);
					this.SendPropertyChanging();
					this._IdResidenza = value;
					this.SendPropertyChanged("IdResidenza");
					this.OnIdResidenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVaccino", DbType="Int NOT NULL")]
		public int IdVaccino
		{
			get
			{
				return this._IdVaccino;
			}
			set
			{
				if ((this._IdVaccino != value))
				{
					this.OnIdVaccinoChanging(value);
					this.SendPropertyChanging();
					this._IdVaccino = value;
					this.SendPropertyChanged("IdVaccino");
					this.OnIdVaccinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPatologia", DbType="Int")]
		public System.Nullable<int> IdPatologia
		{
			get
			{
				return this._IdPatologia;
			}
			set
			{
				if ((this._IdPatologia != value))
				{
					this.OnIdPatologiaChanging(value);
					this.SendPropertyChanging();
					this._IdPatologia = value;
					this.SendPropertyChanged("IdPatologia");
					this.OnIdPatologiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOspedale", DbType="Int NOT NULL")]
		public int IdOspedale
		{
			get
			{
				return this._IdOspedale;
			}
			set
			{
				if ((this._IdOspedale != value))
				{
					this.OnIdOspedaleChanging(value);
					this.SendPropertyChanging();
					this._IdOspedale = value;
					this.SendPropertyChanged("IdOspedale");
					this.OnIdOspedaleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="covid19vaccinetracker.patologia")]
	public partial class patologia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPatologia;
		
		private string _NomePatologia;
		
		private string _Descrizione;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPatologiaChanging(int value);
    partial void OnIdPatologiaChanged();
    partial void OnNomePatologiaChanging(string value);
    partial void OnNomePatologiaChanged();
    partial void OnDescrizioneChanging(string value);
    partial void OnDescrizioneChanged();
    #endregion
		
		public patologia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPatologia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPatologia
		{
			get
			{
				return this._IdPatologia;
			}
			set
			{
				if ((this._IdPatologia != value))
				{
					this.OnIdPatologiaChanging(value);
					this.SendPropertyChanging();
					this._IdPatologia = value;
					this.SendPropertyChanged("IdPatologia");
					this.OnIdPatologiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomePatologia", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string NomePatologia
		{
			get
			{
				return this._NomePatologia;
			}
			set
			{
				if ((this._NomePatologia != value))
				{
					this.OnNomePatologiaChanging(value);
					this.SendPropertyChanging();
					this._NomePatologia = value;
					this.SendPropertyChanged("NomePatologia");
					this.OnNomePatologiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrizione", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Descrizione
		{
			get
			{
				return this._Descrizione;
			}
			set
			{
				if ((this._Descrizione != value))
				{
					this.OnDescrizioneChanging(value);
					this.SendPropertyChanging();
					this._Descrizione = value;
					this.SendPropertyChanged("Descrizione");
					this.OnDescrizioneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="covid19vaccinetracker.residenza")]
	public partial class residenza : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdResidenza;
		
		private string _Citta;
		
		private string _Provincia;
		
		private int _CAP;
		
		private int _TotaleVaccinati;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdResidenzaChanging(int value);
    partial void OnIdResidenzaChanged();
    partial void OnCittaChanging(string value);
    partial void OnCittaChanged();
    partial void OnProvinciaChanging(string value);
    partial void OnProvinciaChanged();
    partial void OnCAPChanging(int value);
    partial void OnCAPChanged();
    partial void OnTotaleVaccinatiChanging(int value);
    partial void OnTotaleVaccinatiChanged();
    #endregion
		
		public residenza()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdResidenza", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdResidenza
		{
			get
			{
				return this._IdResidenza;
			}
			set
			{
				if ((this._IdResidenza != value))
				{
					this.OnIdResidenzaChanging(value);
					this.SendPropertyChanging();
					this._IdResidenza = value;
					this.SendPropertyChanged("IdResidenza");
					this.OnIdResidenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Citta", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Citta
		{
			get
			{
				return this._Citta;
			}
			set
			{
				if ((this._Citta != value))
				{
					this.OnCittaChanging(value);
					this.SendPropertyChanging();
					this._Citta = value;
					this.SendPropertyChanged("Citta");
					this.OnCittaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provincia", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Provincia
		{
			get
			{
				return this._Provincia;
			}
			set
			{
				if ((this._Provincia != value))
				{
					this.OnProvinciaChanging(value);
					this.SendPropertyChanging();
					this._Provincia = value;
					this.SendPropertyChanged("Provincia");
					this.OnProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAP", DbType="Int NOT NULL")]
		public int CAP
		{
			get
			{
				return this._CAP;
			}
			set
			{
				if ((this._CAP != value))
				{
					this.OnCAPChanging(value);
					this.SendPropertyChanging();
					this._CAP = value;
					this.SendPropertyChanged("CAP");
					this.OnCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotaleVaccinati", DbType="Int NOT NULL")]
		public int TotaleVaccinati
		{
			get
			{
				return this._TotaleVaccinati;
			}
			set
			{
				if ((this._TotaleVaccinati != value))
				{
					this.OnTotaleVaccinatiChanging(value);
					this.SendPropertyChanging();
					this._TotaleVaccinati = value;
					this.SendPropertyChanged("TotaleVaccinati");
					this.OnTotaleVaccinatiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="covid19vaccinetracker.vaccinazione")]
	public partial class vaccinazione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _DataEffettuazione;
		
		private int _nRichiamo;
		
		private System.DateTime _DataRichiamo;
		
		private int _IdPaziente;
		
		private int _IdInfermiere;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDataEffettuazioneChanging(System.DateTime value);
    partial void OnDataEffettuazioneChanged();
    partial void OnnRichiamoChanging(int value);
    partial void OnnRichiamoChanged();
    partial void OnDataRichiamoChanging(System.DateTime value);
    partial void OnDataRichiamoChanged();
    partial void OnIdPazienteChanging(int value);
    partial void OnIdPazienteChanged();
    partial void OnIdInfermiereChanging(int value);
    partial void OnIdInfermiereChanged();
    #endregion
		
		public vaccinazione()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataEffettuazione", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DataEffettuazione
		{
			get
			{
				return this._DataEffettuazione;
			}
			set
			{
				if ((this._DataEffettuazione != value))
				{
					this.OnDataEffettuazioneChanging(value);
					this.SendPropertyChanging();
					this._DataEffettuazione = value;
					this.SendPropertyChanged("DataEffettuazione");
					this.OnDataEffettuazioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nRichiamo", DbType="Int NOT NULL")]
		public int nRichiamo
		{
			get
			{
				return this._nRichiamo;
			}
			set
			{
				if ((this._nRichiamo != value))
				{
					this.OnnRichiamoChanging(value);
					this.SendPropertyChanging();
					this._nRichiamo = value;
					this.SendPropertyChanged("nRichiamo");
					this.OnnRichiamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataRichiamo", DbType="Date NOT NULL")]
		public System.DateTime DataRichiamo
		{
			get
			{
				return this._DataRichiamo;
			}
			set
			{
				if ((this._DataRichiamo != value))
				{
					this.OnDataRichiamoChanging(value);
					this.SendPropertyChanging();
					this._DataRichiamo = value;
					this.SendPropertyChanged("DataRichiamo");
					this.OnDataRichiamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPaziente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdPaziente
		{
			get
			{
				return this._IdPaziente;
			}
			set
			{
				if ((this._IdPaziente != value))
				{
					this.OnIdPazienteChanging(value);
					this.SendPropertyChanging();
					this._IdPaziente = value;
					this.SendPropertyChanged("IdPaziente");
					this.OnIdPazienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdInfermiere", DbType="Int NOT NULL")]
		public int IdInfermiere
		{
			get
			{
				return this._IdInfermiere;
			}
			set
			{
				if ((this._IdInfermiere != value))
				{
					this.OnIdInfermiereChanging(value);
					this.SendPropertyChanging();
					this._IdInfermiere = value;
					this.SendPropertyChanged("IdInfermiere");
					this.OnIdInfermiereChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="covid19vaccinetracker.vaccino")]
	public partial class vaccino : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVaccino;
		
		private string _Nome;
		
		private string _CasaFarmaceutica;
		
		private int _Richiamo;
		
		private string _Info;
		
		private int _PrezzoUnitario;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVaccinoChanging(int value);
    partial void OnIdVaccinoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCasaFarmaceuticaChanging(string value);
    partial void OnCasaFarmaceuticaChanged();
    partial void OnRichiamoChanging(int value);
    partial void OnRichiamoChanged();
    partial void OnInfoChanging(string value);
    partial void OnInfoChanged();
    partial void OnPrezzoUnitarioChanging(int value);
    partial void OnPrezzoUnitarioChanged();
    #endregion
		
		public vaccino()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVaccino", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVaccino
		{
			get
			{
				return this._IdVaccino;
			}
			set
			{
				if ((this._IdVaccino != value))
				{
					this.OnIdVaccinoChanging(value);
					this.SendPropertyChanging();
					this._IdVaccino = value;
					this.SendPropertyChanged("IdVaccino");
					this.OnIdVaccinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NChar(15) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CasaFarmaceutica", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string CasaFarmaceutica
		{
			get
			{
				return this._CasaFarmaceutica;
			}
			set
			{
				if ((this._CasaFarmaceutica != value))
				{
					this.OnCasaFarmaceuticaChanging(value);
					this.SendPropertyChanging();
					this._CasaFarmaceutica = value;
					this.SendPropertyChanged("CasaFarmaceutica");
					this.OnCasaFarmaceuticaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Richiamo", DbType="Int NOT NULL")]
		public int Richiamo
		{
			get
			{
				return this._Richiamo;
			}
			set
			{
				if ((this._Richiamo != value))
				{
					this.OnRichiamoChanging(value);
					this.SendPropertyChanging();
					this._Richiamo = value;
					this.SendPropertyChanged("Richiamo");
					this.OnRichiamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Info", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Info
		{
			get
			{
				return this._Info;
			}
			set
			{
				if ((this._Info != value))
				{
					this.OnInfoChanging(value);
					this.SendPropertyChanging();
					this._Info = value;
					this.SendPropertyChanged("Info");
					this.OnInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrezzoUnitario", DbType="Int NOT NULL")]
		public int PrezzoUnitario
		{
			get
			{
				return this._PrezzoUnitario;
			}
			set
			{
				if ((this._PrezzoUnitario != value))
				{
					this.OnPrezzoUnitarioChanging(value);
					this.SendPropertyChanging();
					this._PrezzoUnitario = value;
					this.SendPropertyChanged("PrezzoUnitario");
					this.OnPrezzoUnitarioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
