<?xml version="1.0" encoding="utf-8"?><Database Name="Covid19Tracker" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDb)\Covid19Track;Initial Catalog=Covid19Tracker;Integrated Security=True" SettingsObjectName="OspedaleEVaccinazioni.Properties.Settings" SettingsPropertyName="Covid19TrackerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="covid19vaccinetracker.dosi" Member="dosi">
    <Type Name="dosi">
      <Column Name="IdVaccino" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdOspedale" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TotDosi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="covid19vaccinetracker.fornitore" Member="fornitore">
    <Type Name="fornitore">
      <Column Name="IdFornitore" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NomeFornitore" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="IdVaccino" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="covid19vaccinetracker.infermiere" Member="infermiere">
    <Type Name="infermiere">
      <Column Name="IdInfermiere" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DataNascita" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Sesso" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CodFiscale" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DataAssunzione" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IdOspedale" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="covid19vaccinetracker.ospedale" Member="ospedale">
    <Type Name="ospedale">
      <Column Name="IdOspedale" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Indirizzo" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="covid19vaccinetracker.paziente" Member="paziente">
    <Type Name="paziente">
      <Column Name="IdPaziente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cognome" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DataNascita" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Sesso" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="CodFiscale" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="IdResidenza" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdVaccino" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPatologia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdOspedale" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="covid19vaccinetracker.patologia" Member="patologia">
    <Type Name="patologia">
      <Column Name="IdPatologia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NomePatologia" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Descrizione" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="covid19vaccinetracker.residenza" Member="residenza">
    <Type Name="residenza">
      <Column Name="IdResidenza" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Citta" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CAP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotaleVaccinati" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="covid19vaccinetracker.vaccinazione" Member="vaccinazione">
    <Type Name="vaccinazione">
      <Column Name="DataEffettuazione" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nRichiamo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataRichiamo" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IdPaziente" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdInfermiere" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="covid19vaccinetracker.vaccino" Member="vaccino">
    <Type Name="vaccino">
      <Column Name="IdVaccino" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CasaFarmaceutica" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Richiamo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Info" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PrezzoUnitario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>